In [1]:
import pandas as pd
df = pd.read_csv('A_LVR_LAND.csv',encoding='big5')
df.head()

  鄉鎮市區  建物移轉總面積平方公尺  建物現況格局-房  建物現況格局-廳       總價元  單價每平方公尺
0  文山區        90.63         3         2  12000000   132406
1  北投區       164.59         5         2  11800000    71693
2  萬華區        34.15         1         1   8200000   240117
3  萬華區        43.40         1         1   9000000   207373
4  萬華區        40.95         0         1   9520000   232479

In [2]:
df2 = pd.get_dummies(df['鄉鎮市區'])
df2.head()

   中山區  中正區  信義區  內湖區  北投區  南港區  士林區  大同區  大安區  文山區  松山區  萬華區
0    0    0    0    0    0    0    0    0    0    1    0    0
1    0    0    0    0    1    0    0    0    0    0    0    0
2    0    0    0    0    0    0    0    0    0    0    0    1
3    0    0    0    0    0    0    0    0    0    0    0    1
4    0    0    0    0    0    0    0    0    0    0    0    1

In [3]:
df.join(df2).head()

,鄉鎮市區,建物移轉總面積平方公尺,建物現況格局-房,建物現況格局-廳,總價元,單價每平方公尺,中山區,中正區,信義區,內湖區,北投區,南港區,士林區,大同區,大安區,文山區,松山區,萬華區
0,文山區,90.63,3,2,12000000,132406,0,0,0,0,0,0,0,0,0,1,0,0
1,北投區,164.59,5,2,11800000,71693,0,0,0,0,1,0,0,0,0,0,0,0
2,萬華區,34.15,1,1,8200000,240117,0,0,0,0,0,0,0,0,0,0,0,1
3,萬華區,43.40,1,1,9000000,207373,0,0,0,0,0,0,0,0,0,0,0,1
4,萬華區,40.95,0,1,9520000,232479,0,0,0,0,0,0,0,0,0,0,0,1